version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - export BUCKET=lambda-deployment-artifacts-rayas-1
      - echo "first serverless deployment"
      - echo "testing PR trigger"
      
      
